# remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# mouse mode
set -g mouse on

# bells
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# focus events
set-option -g focus-events on

# don't rename windows automatically
set-option -g allow-rename off

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# next / previous window bindings
bind-key C-p previous-window
bind-key C-n next-window

# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf; display "Loaded tmux.conf"

# window numbers
set -g base-index 1
set-option -g renumber-windows on

# status bar
set -g status-position top
set -g status-justify left
set -g status-style fg=black,bg=#ffffff
set -g status-left "[#S] "
set -g status-right ""
set -g window-status-format "#I:#W#{?window_flags,#{window_flags}, }"
set -g window-status-current-style "fg=black bold,bg=#ffffff"

# messages
set -g message-style 'fg=black bg=yellow'

