{:user {:plugins [[cider/cider-nrepl "0.10.0"]
                  [venantius/ultra "0.4.0"]
                  [lein-try "0.4.3"]
                  [lein-simpleton "1.3.0"]
                  [jonase/eastwood "0.2.1"]
                  [lein-kibit "0.1.2"]
                  [lein-ancient "0.6.8"]
                  [lein-bikeshed "0.2.0"]
                  [lein-exec "0.3.5"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}
